---

- name: Create a ext4 filesystem on /dev/sdc
  filesystem:
    fstype: ext4
    dev: /dev/sdc

- name: Mount up disk
  mount:
    path: "{{ jenkins_root }}"
    src: /dev/sdc
    fstype: ext4
    state: mounted