---
- name: Ensure dependencies are installed.
  apt:
    name:
      - python-pip
    state: present

- name: Setup directories
  file:
    path: "{{ item }}"
    owner: "{{ jenkins_admin_username }}"
    group: "{{ jenkins_admin_username }}"
    mode: 0775
    state: directory
  with_items:
    - "{{ jenkins_home }}"
  become: true

- name: Install apt requirements
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - ca-certificates-java
    - openjdk-8-jre-headless
    - sudo

- name: correct java version selected
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

- name: Make jenkins user sudoer
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: '{{ jenkins_admin_username }}	ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'

# - name: Add master public key to authorized keys
#   authorized_key:
#     user: '{{ jenkins_admin_username }}'
#     key: '{{ jenkins_authorized_key }}'