jenkins_master_servers:
  hosts:
    prod-jenkins-master-server-00:
      ansible_user: "{{ ansible_user }}"
      ansible_host: "{{ jenkins_master_domain }}"

jenkins_slave_servers:
  hosts:
    prod-jenkins-slave-server-00:
      ansible_user: "{{ ansible_user }}"
      ansible_host: "{{ jenkins_slave_0_domain }}"
